### ISSUE TITLE
Rinominare il repository in "parlamentari"

### ISSUE THREAD

**Issue by fpietrosanti** [rm76/deputati-e-senatori#6]
Nel non limitarsi ai soli deputati, rinominare il repository in "parlamentari"

**Comment by rm76** [comment]
Ok, però il repo lo chiamerei "deputati e senatori" perché la Costituzione li chiama così, non si riferisce mai a loro chiamandoli "parlamentari", che sebbene sia entrato nel linguaggio comune, mi suona più come un aggettivo.

**Comment by fpietrosanti** [comment]
daje!
